### ISSUE TITLE
gok.sh uses tempfile, it should use the more widely available mktemp

### ISSUE THREAD

**Issue by chrissexton** [eaburns/T#117]
Seen in #116, gok.sh isn't really doing a great job of working. @mccoyst found that `tempfile` doesn't exist on OS X and I checked out the repo to verify what the issue is to find out that my "basic" Arch install also does not have `tempfile`. `mktemp` works for me, but apparently is slightly different on OS X.

Beyond that, I needed to `set -x` to see what step was actually failing in the script. Some more descriptive fail conditions (maybe make it take a string and print that out?) would probably go a long way.

**Comment by mccoyst** [comment]
For the OS X part, the usage is e.g.

    mktemp blahXXXXX

where the X's are of any number, but have to be at the end.

**Comment by chrissexton** [comment]
You may specify that template on the version I have locally as well and `--tmpdir` is implied.

**Comment by eaburns** [comment]
I don't understand the "doesn't report great errors" part. If golint fails, the errors follow the comment "Linting." I'm going to make this issue solely about chaning `tempfile` to `mktemp`.
