### ISSUE TITLE
support split machine operation

### ISSUE THREAD

**Issue by rogpeppe** [eaburns/T#127]
One of the main drawbacks (well, possibly *the* only drawback) of acme
vs sam is that sam supports split operation, where the front-end runs
on one machine and the back-end runs remotely. This provides
great benefits when working over a high-latency connection.

It's also something that needs to be worked in at a low level,
so it may be worth considering now. Even more interesting might
be to allow multiple clients to interact with the same backend.

**Comment by eaburns** [comment]
That's exactly the plan.

I haven't shared it until just now, but here are my notes:
https://docs.google.com/document/d/1a6HoqavYRvn6OWaxeg4PGVEbnxM0VYm_ekjishCnM8s/edit?usp=sharing

It still needs a lot more thought. For example, that be efficient enough? How to do syntax highlighting when the client doesn't hold the entire buffer? (I don't care about it, but lack of syntax highlighting is a non-starter for most.)

**Comment by eaburns** [comment]
I'm going to close this issue. Of course the plan is to do it, but the issue itself is not particularly actionable. It's simply part of the design.
