### ISSUE TITLE
Ditch re1. Use regexp.

### ISSUE THREAD

**Issue by eaburns** [eaburns/T#172]
# Background

I initially wrote re1 because the regexp package isn't an exact fit for our needs:
 1. It doesn't support reverse-match compilation.
 2. It always starts from the beginning of the input, never the middle.

  a. It doesn't support wrapping.

  b. It won't correctly handle ^, when the beginning of its input is not actually the start of a line. (Try the address: `1-+#1/bc` on the input `abc`. Then try `1-+#1/^bc`.)

 3. It reports indexes as byte offsets.
 4. I don't think that it supported returning indexes given a RuneReader when I started re1.

It was easier to write a new, tiny regexp package implementing good old plan9/sam/acme regular expressions. This is the only subset of regular expressions that I use anyway.

# Problem

But re1 is becoming a burden.

The biggest flaw with re1 is that it doesn't accept a modern regulax expression language. A modern editor should understand modern regexps (and by modern, at this point, we really mean stuff that existed all the way back in the 90s).

Another, more recent flaw with re1 is that it requires rune-level indexing into its input. This is how it solves problem 2 listed above. But we want to switch the T backend to use UTF8 instead of runes (see #134). After the switch, we won't have efficient, rune-level indexing.

# Solution

We should switch to using regexp. I have a proposed solution for each of the problems, 1-4, listed above.

 1. We don't _need_ reverse match support. It can be simulated by running the regexp forward up until the start point and returning the last-found match. Asymptotically, this is no more expensive than running the reverse match, because in the worst case there is no match and either way we have to check the entire file.

 2. We can use two tricks:

  a. We don't need regexp to know about wrapping. Instead, the edit package can run the regexp twice: once from the starting point forward to $ and, if no match, again from 0 to $. The second match is more expensive than what re1 currently does. re1 will not consider the regexp further after it re-reaches the starting point. It knows that it already checked the rest of the file. However, that optimization only gains a constant factor. At worse, we would now do two runs of the regexp over the file instead of one.

  b. To simulate a non-beginning-of-line match, we can insert a dummy rune before the first rune of the match. The dummy rune is not \n, so it won't be a beginning of line. Since we choose the dummy rune and its width, we can select a rune that will never match (utf8.RuneError) and a known width (1). If there is a match, we simply subtract the dummy width from of the match indices. See http://play.golang.org/p/w4gOWDKPo9 for a demo.

 3. Before switching the backend to UTF8, we can do a pass over the file to compute the rune indices for the corresponding byte indices. This is anoter pass over the file, which is sad, but it'll be temporary. After switching over, we should convert everything to use byte indices anyway. Then it'll be free.
 
 4. regexp.FindReaderIndex is there and ready to be used.

**Comment by eaburns** [comment]
For 2a, we could simply consider not supporting wrapping around. @mccoyst claims that it is a useless feature.

**Comment by mccoyst** [comment]
:+1:

**Comment by eaburns** [comment]
If we don't do wrapping, ? regexps become useless. They currently rely on the fact that search from #0 wraps to end of file and starts again from the bottom up.

If we get rid of wrapping, we should get rid of ? regexps too. They are clumsy because ? is a meta character, and you can use - before a forward regexp to get the same effect: `$-/abc/`.

**Comment by mccoyst** [comment]
That makes sense, regarding ? — that kind of thing is best handled by the edit language.

**Comment by mccoyst** [comment]
1. I think this is an acceptable behavior. But, if you really don't like it, you can probably define something like a RuneLimitedReader that stops at dot, and pass that into regexp.FindReaderIndex etc.

2. No special case for ^ is necessary. Slap on multiline mode when needed: http://play.golang.org/p/Fq14BXWuGH

**Comment by eaburns** [comment]
1. I was convinced that limiting the reader wouldn't work. (Actually, my reader is already limited, but I always set the limit to EOF.) But now that I think about it again, you're right. I think that it would work.

 2. However, multi-line mode doesn't solve this problem. In fact, I always set multi-line mode (if you are interested, the current code is here: https://github.com/eaburns/T/blob/regexp/edit/regexp.go). The problem is that multi-line mode still always assumes that the first rune of input is the "beginning of text." In T, this isn't always the case. If a Regexp address are always computed relative to another address (either dot, or the left-hand-side of a + or -) and Substitute edits are bounded by an address range. There is no restriction that the first rune of either of these is the beginning of text or even the beginning of a line.

 Consider the text `abcabc\nabc` In acme or sam, try `#3+/^abc/`. It starts matching at #3, so the string given to the regexp package is `abc\nabc`. Logically, the first abc is not the beginning of text or the beginning of a line; it's three runes into line 1. However, seeing it at the beginnig, regexp will treat it as beginning of text even if it has multi-line mode set. The match will be the abc at the end of line 1, instead of line 2.

**Comment by eaburns** [comment]
Update on 1. Limiting reader causes breaking akin to 2: now there are false $ matches when the limited reader returns EOF.

**Comment by eaburns** [comment]
Update on the update on 1. I fixed it by adding a trailing dummy rune for mid-line ends.

**Comment by eaburns** [comment]
We decided to fix 2b by simply re-defining it not to be a BUG. The relative start of a regexp address or the range end points of a substitute are considered to be the beginning of or end of the text.
