### ISSUE TITLE
Rewrite edit tests using better notation.

### ISSUE THREAD

**Issue by eaburns** [eaburns/T#173]
The edit tests need to be fixed. They are hard to read, hard to debug debug, and are brittle to changes like #134.

# Background

There are three problems. The first, and biggest, is that they use internal details to verify that dot and marks get set correctly. Namely, they use `addr{}`, which, currently, has the rune offsets of the address. This is not easy for humans to read and debug, and it's brittle to changes of the `addr{}` representation. For example, in #134, we would like to change it to use byte offsets instead of rune offsets.

The second problem is that the tests do too many things in one place. Each test entry runs the entry, then stringifies and re-parses the edit and runs it again. This means that when something breaks, lots of lines of breakage are dumped and it's hard to tell which are the original tests and which are the string-re-parsed tests.

The third is that the tests only support a single edit. Testing Undo and Redo requires multiple edits, so these tests need their own infrastructure. It should be merged.

## Address tests

The address tests are actually even bigger offenders. They exclusively test internal behavior: the _unexported_ `whereFrom` method. They also rely even more on non-human-readable `addr{}`s. These should instead be tested using the edit test framework in the same way that edits are tested.

# Solution

I propose we redo the tests. I think that lots of this can be done mechanically. The main improvement is to introduce a simple human-readable notation to describe a buffer and its marks, including dot. The notation is a simple string, however, any punctuation marks in the string are interpreted as denoting the start or end of a mark — no numbers needed.

## Examples

Instead of:
```
{
	init: "Hello, 世界!",
	e:    Change(End, "XYZ"),
	want: "Hello, 世界!XYZ",
	dot:  addr{10, 13},
}
```
It would look like this:
```
{
	given: "..Hello 世界", // Dot begins at #0.
	do:    []Edit{ Change(End, "XYZ") },
	want: "Hello 世界.XYZ.", // Dot moves to #10,#13.
}
```
(Note the need to remove punctuation that is not indicating a mark range. Should be fine.)

Instead of:
```
{
	init: "Hello, 世界!",
	e: Set(All, 'a'),
	want: "Hello, 世界!",
	marks: map[rune]addr{'a': addr{0, 10}},
}
```
It would look like this:
```
{
	given: "..Hello 世界",
	do: []Edit{Set(All, ';')},
	want: "..;Hello 世界;",
}
```

## Testing strings and re-parsing

Testing the string-re-parse of an edit should be explicit. In addition to a `run` method, the new `editTest` type will have a `runFromString` method, which is just like `run` but runs on the string-re-parse of the edits. This can be called explicitly from a separate test function, so that the output will be clear which failures are from the original test and which are from the string-re-parse version. They will each be grouped under different TestXYZ headers. This also allows one to use the -test.run flag to exclude the FromString tests or the non-FromString tests if needed.

```
var substituteTests = …
func TestEditSubstitute(t *testing.T) {
  for _, test := range substituteTests {
    test.run(t)
  }
}

func TestEditSubstituteFromString(t *testing.T) {
  for _, test := range substituteTests {
    test.runFromString(t)
  }
}
```

## Address tests

Address tests should use this new edit test framework. This way, they can both leverage the new, human-readable notation and test external behavior instead of internal. This will be done using the `Set` edit.

Instead of:
```
{
	text: "abc\ndef",
	dot: rng(1, 6),
	addr: Dot.Minus(Line(1)).Plus(Line(1)), 
	want: rng(0, 4),
}
```
It will be:
```
// address returns an []Edit which sets . to the given address.
func address(a Address) []Edit { return []Edit{Set(a, '.')} }

{
	given: "a.bc\nde.f",
	do: address(Dot.Minus(Line(1)).Plus(Line(1))), 
	want: ".abc\n.def",
}
```

**Comment by mccoyst** [comment]
Sounds good, although it might get confusing to use . here, since it is a metacharacter in regexes. Maybe · ?

**Comment by eaburns** [comment]
I think that it should be fine. In all such cases, the string represents the contents of the buffer, not an edit string.

**Comment by eaburns** [comment]
It turns out that using punctuation makes things a bit obscure. We end up with tests like:
```
{
	name:  "insert updates marks",
	given: "..:abc:;123;,xyz,",
	do:    []Edit{Change(Regexp("2"), "xxx")},
	want:  ":abc:;1.xxx.3;,xyz,",
},
```
I also argued that overlap between mark punctuation and regexp meta characters isn't a problem. Actually, it is. We want to test regexps with escaped meta characters and such to make sure that they match strings in the buffer. If we can't make buffers with such strings, then we cannot make such tests.

Instead, @mccoyst proposed a new notation, which is a bit more heavy-weight, but should solve these problems. Runes between { and } are marks. `·` is shorthand for `{.}`. So the above test would look like this:
```
{
	name:  "insert updates marks",
	given: "··{m}abc{mn}123{no}xyz{o}",
	do:    []Edit{Change(Regexp("2"), "xxx")},
	want:  "{m}abc{mn}1·xxx·3{no}xyz{o}",
},
```

**Comment by eaburns** [comment]
In fact, I'm not sure it's even worth having the shorthand for dot. `{.}` Is fine.
