### ISSUE TITLE
ui: copy/paste

### ISSUE THREAD

**Issue by eaburns** [eaburns/T#4]
We should use the system clipboard if possible. An easy way to start is to write a package that wraps `xclip` for Linux and the corresponding program for OSX.

Does Windows have such a program?

Eventually, we should probably write a small cgo package to provide copy/paste for major OSes.

**Comment by ktye** [comment]
This package has clipboard for multiple os, including windows via win32:
https://github.com/atotto/clipboard

**Comment by eaburns** [comment]
Thanks.
