### ISSUE TITLE
Implement Loop (x) Edit command.

### ISSUE THREAD

**Issue by eaburns** [eaburns/T#82]
And y.

**Comment by eaburns** [comment]
@leGoof, did you decide that you wanted to do this one?

**Comment by leGoof** [comment]
yup i'll get it shortly.

**Comment by eaburns** [comment]
No rush. I was just scanning the issue tracker to see which I should tackle next and saw that this was unassigned.

**Comment by eaburns** [comment]
@leGoof, I'm stealing this from you.
